services:

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    container_name: product-service # comment this line when to do load testing
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=mrscrapershop
      - DB_PASSWORD=mrscrapershop123
      - DB_DATABASE=mrscrapershop_db
      - REDIS_HOST=redis://redis:6379
      - RABBITMQ_HOST=amqp://guest:guest@rabbitmq:5672
    volumes:
      - ./product-service:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    networks:
      - mrscrapershop-net
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: on-failure

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: order-service
    environment:
      - DATABASE_HOST=postgres://mrscrapershop:mrscrapershop123@db:5432/mrscrapershop_db?sslmode=disable
      - REDIS_HOST=redis://redis:6379
      - RABBITMQ_HOST=amqp://guest:guest@rabbitmq:5672
      - PRODUCT_SERVICE_URL=http://product-service:3000
    volumes:
      - ./order-service:/app
    command: air
    networks:
      - mrscrapershop-net
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      product-service:
        condition: service_started
    restart: on-failure

  db:
    image: postgres:18-alpine
    container_name: db
    environment:
      - POSTGRES_USER=mrscrapershop
      - POSTGRES_PASSWORD=mrscrapershop123
      - POSTGRES_DB=mrscrapershop_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c 'max_connections=500' -c 'commit_delay=1000' -c 'commit_siblings=5' -c 'shared_buffers=512MB'
    networks:
      - mrscrapershop-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mrscrapershop -d mrscrapershop_db"]
      interval: 20s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - mrscrapershop-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - mrscrapershop-net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  bff-service:
    build: 
      context: ./bff-service
      dockerfile: Dockerfile
    container_name: bff-service # comment this line when to do load testing
    ports: # comment this line when to do load testing
      - "8000:8000" # comment this line when to do load testing
    environment:
      - PORT=8000
      - PRODUCT_SERVICE_URL=http://product-service:3000
      - ORDER_SERVICE_URL=http://order-service:8080
    networks:
      - mrscrapershop-net
    depends_on:
      - product-service
      - order-service
    restart: on-failure
    
volumes:
  postgres_data:
    driver: local

networks:
  mrscrapershop-net:
    driver: bridge